{
    'name': 'Prestamos Universidad',
    'version': '18.0.1.0',
    'category': 'Education',
    'summary': 'Registro y control de prestamos de equipos y libros universitarios.',
    'author': 'Kristhian Jose Ortiz Arteaga, Luis Fernando Cerruto Salas, Vicente Gerardo Aguilera Vera',
    'depends': ['base', 'mail'],
    'data': [
        'security/prestamos_universidad_security.xml',
        'security/ir.model.access.csv',
        'data/prestamos_universidad_data.xml',
        'views/prestamo_categoria_views.xml',
        'views/prestamo_area_views.xml',
        'views/prestamo_sancion_views.xml',
        'views/res_users_views.xml',
        'views/prestamo_recurso_views.xml',
        'views/prestamo_prestamo_views.xml',
        'views/prestamo_mantenimiento_views.xml',
        'views/prestamo_reportes_views.xml',
        'views/prestamos_universidad_menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'prestamos_universidad/static/src/scss/prestamo_dashboard.scss',
        ],
    },
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
